### ISSUE TITLE
a little mistake in README.md usage

### ISSUE THREAD

**Issue by dalmamad** [kkocdko/hello-napi#1]
hello dear friend. thanks for your instructure.
there is a little mistake in `usage` section in readme file.
here:
g++ src/main.cc -o build/main.node \

you are compiling main.cc and output file is also main.node.
BUT name of the file in src directory is hinapi.cc and also you are exporting hinapi.node in the js file.
that's it.
good luck

**Comment by kkocdko** [comment]
Thank u!
